DROP TABLE IF EXISTS spittle;
DROP TABLE IF EXISTS spitter;

CREATE TABLE spitter (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(25) NOT NULL,
  PASSWORD VARCHAR(25) NOT NULL,
  fullName VARCHAR(100) NOT NULL,
  email VARCHAR(50) NOT NULL,
  updateByEmail BOOLEAN NOT NULL
);

CREATE TABLE spittle (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  spitter INTEGER NOT NULL,
  message VARCHAR(2000) NOT NULL,
  postedTime DATETIME NOT NULL,
  FOREIGN KEY (spitter) REFERENCES spitter(id)
);
